name: Ubuntu
# from https://github.com/jaredtao/HelloActions-Qt/blob/master/.github/workflows/ubuntu.yml
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'README.ko.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'README.ko.md'        
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        qt_ver: [5.12.6]
        qt_arch: [gcc_64]
    steps:
      - name: cacheQt
        id: UbuntuCacheQt
        uses: actions/cache@v1
        with:
          path: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
          key: ${{ runner.os }}-Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}    
      - name: setupQt
        if: steps.UbuntuCacheQt.outputs.cache-hit == 'true'
        shell: pwsh
        env:
          QtPath: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
        run: |
          $qt_Path=${env:QtPath}
          echo "::set-env name=Qt5_Dir::$qt_Path"
          echo "::add-path::$qt_Path/bin"
      - name: Install Qt
        if: steps.UbuntuCacheQt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2.0.0
        with:
          version: ${{ matrix.qt_ver }}
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          cd TestExcel
          ${env:QtPath}/bin/qmake TestExcel.pro
          make

