# base code from https://github.com/jaredtao/HelloActions-Qt
# windows.yml

name: Windows
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'README.ko.md'      
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'README.ko.md'      
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        qt_ver: [5.12.6]
        qt_target: [desktop]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build 
        run: |
          cd TestExcel
          qmake
          nmake


