# base code from https://github.com/jaredtao/HelloActions-Qt
# windows.yml

name: Windows
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
         os: [windows-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: "npm ci"
        run: npm ci
      - name: "npm run build"
        run: npm run build
      - name: Install Qt
        uses: ./
        with:
          modules: qtcharts qtwebengine
      - name: Configure test project on windows
        if: startsWith(matrix.os, 'windows')
        run: |
          cd TestExcel
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          dir %Qt5_Dir%/lib/cmake
          qmake
        shell: cmd


